import 'package:fitbro/utilities/exercises/exercise_class.dart';

final defaultExercises = [
  Exercise("21", "Barbell", "Arms", 1),
  Exercise("Ab wheel", "Weighted Bodyweight", "Core", 2),
  Exercise("Aerobics", "Duration", "Cardio", 3),
  Exercise("Arnorld Press (Dumbbell)", "Dumbbell", "Shoulders", 4),
  Exercise("Around the World", "Dumbbell", "Chest", 5),
  Exercise("Back Extension", "Weighted Bodyweight", "Back", 6),
  Exercise("Back Extension (Machine)", "Machine/Other", "Back", 7),
  Exercise("Ball Slams", "Machine/Other", "Full Body", 8),
  Exercise("Battle Ropes", "Cardio", "Cardio", 9),
  Exercise("Bench Dip", "Weighted Bodyweight", "Arms", 10),
  Exercise("Bench Press (Barbell)", "Barbell", "Chest", 11),
  Exercise("Bench Press (Cable)", "Machine/Other", "Chest", 12),
  Exercise("Bench Press (Dumbbell)", "Dumbbell", "Chest", 13),
  Exercise("Bench Press (Smith Machine)", "Machine/Other", "Chest", 14),
  Exercise("Bench Press - Close Grip (Barbell)", "Barbell", "Arms", 15),
  Exercise("Bench Press - Wide Grip (Barbell)", "Barbell", "Chest", 16),
  Exercise("Bent Over One Arm Row (Dumbbell)", "Dumbbell", "Back", 17),
  Exercise("Bent Over Row (Band)", "Weighted Bodyweight", "Back", 18),
  Exercise("Bent Over Row (Barbell)", "Barbell", "Back", 19),
  Exercise("Bent Over Row (Dumbbell)", "Dumbbell", "Back", 20),
  Exercise("Bent Over Row - Underhand (Barbell)", "Barbell", "Back", 21),
  Exercise("Bicep Curl (Barbell)", "Barbell", "Arms", 22),
  Exercise("Bicep Curl (Cable)", "Machine/Other", "Arms", 23),
  Exercise("Bicep Curl (Dumbbell)", "Dumbbell", "Arms", 24),
  Exercise("Bicep Curl (Machine)", "Machine/Other", "Arms", 25),
  Exercise("Bicycle Crunch", "Weighted Bodyweight", "Core", 26),
  Exercise("Box Jump", "Reps Only", "Legs", 27),
  Exercise("Box Squat (Barbell)", "Barbell", "Legs", 28),
  Exercise("Bulgarian Split Squat", "Barbell", "Legs", 29),
  Exercise("Burpee", "Reps Only", "Full Body", 30),
  Exercise("Cable Crossover", "Machine/Other", "Chest", 31),
  Exercise("Cable Crunch", "Machine/Other", "Core", 32),
  Exercise("Cable Kickback", "Machine/Other", "Arms", 33),
  Exercise("Cable Pull Through", "Machine/Other", "Legs", 34),
  Exercise("Cable Twist", "Machine/Other", "Core", 35),
  Exercise("Calf Press on Leg Press", "Machine/Other", "Legs", 36),
  Exercise("Calf Press on Seated Leg Press", "Machine/Other", "Legs", 37),
  Exercise("Chest Dip", "Weighted Bodyweight", "Chest", 38),
  Exercise("Chest Dip (Assisted)", "Assisted Body", "Chest", 39),
  Exercise("Chest Fly", "Machine/Other", "Chest", 40),
  Exercise("Chest Fly (Band)", "Weighted Bodyweight", "Chest", 41),
  Exercise("Chest Fly (Dumbbell)", "Dumbbell", "Chest", 42),
  Exercise("Chest Press (Band)", "Weighted Bodyweight", "Chest", 43),
  Exercise("Chest Press (Machine)", "Machine/Other", "Chest", 44),
  Exercise("Chin Up", "Weighted Bodyweight", "Back", 45),
  Exercise("Chin Up (Assisted)", "Assisted Body", "Back", 46),
  Exercise("Clean (Barbell)", "Barbell", "Olympic", 47),
  Exercise("Clean and Jerk (Barbell)", "Barbell", "Olympic", 48),
  Exercise("Climbing", "Duration", "Cardio", 49),
  Exercise("Concentration Curl (Dumbbell)", "Dumbbell", "Arms", 50),
  Exercise("Cross Buddy Crunch", "Weighted Bodyweight", "Core", 51),
  Exercise("Cable Crossover - Lower Chest", "Machine/Other", "Core", 52),
  Exercise("Crunch", "Weighted Bodyweight", "Core", 53),
  Exercise("Crunch (Machine)", "Machine/Other", "Core", 54),
  Exercise("Crunch (Stability Ball)", "Reps Only", "Core", 55),
  Exercise("Cycling", "Cardio", "Cardio", 56),
  Exercise("Cycling (Indoor)", "Cardio", "Cardio", 57),
  Exercise("Deadlift (Band)", "Weighted Bodyweight", "Legs", 58),
  Exercise("Deadlift (Barbell)", "Barbell", "Back", 59),
  Exercise("Deadlift (Dumbbell)", "Dumbbell", "Legs", 60),
  Exercise("Deadlift (Smith Machine)", "Machine/Other", "Legs", 61),
  Exercise("Deadlift High Pull (Barbell)", "Barbell", "Olympic", 62),
  Exercise("Decline Bench Press (Barbell)", "Barbell", "Chest", 63),
  Exercise("Decline Bench Press (Dumbbell)", "Dumbbell", "Chest", 64),
  Exercise("Decline Bench Press (Smith Machine)", "Machine/Other", "Chest", 65),
  Exercise("Decline Crunch", "Weighted Bodyweight", "Core", 66),
  Exercise("Deficit Deadlift (Barbell)", "Barbell", "Legs", 67),
  Exercise("Elliptical Machine", "Cardio", "Cardio", 68),
  Exercise("Face Pull (Cable)", "Machine/Other", "Shoulders", 69),
  Exercise("Flat Knee Raise", "Reps Only", "Core", 70),
  Exercise("Flat Leg Raise", "Reps Only", "Core", 71),
  Exercise("Floor Press (Barbell)", "Barbell", "Chest", 72),
  Exercise("Front Raise (Band)", "Weighted Bodyweight", "Shoulders", 73),
  Exercise("Front Raise (Barbell)", "Barbell", "Shoulders", 74),
  Exercise("Front Raise (Cable)", "Machine/Other", "Shoulders", 75),
  Exercise("Front Raise (Dumbbell)", "Dumbbell", "Shoulders", 76),
  Exercise("Front Raise (Plate)", "Machine/Other", "Shoulders", 77),
  Exercise("Front Squat (Barbell)", "Barbell", "Legs", 78),
  Exercise("Glute Ham Raise", "Weighted Bodyweight", "Legs", 79),
  Exercise("Glute Kickback (Machine)", "Machine/Other", "Legs", 80),
  Exercise("Goblet Squat (Kettlebell)", "Machine/Other", "Legs", 81),
  Exercise("Good Morning (Barbell)", "Barbell", "Back", 82),
  Exercise("Hack Squat", "Machine/Other", "Legs", 83),
  Exercise("Hack Squat (Barbell)", "Barbell", "Legs", 84),
  Exercise("Hammer Curl (Band)", "Weighted Bodyweight", "Arms", 85),
  Exercise("Hammer Curl (Cable)", "Machine/Other", "Arms", 86),
  Exercise("Hammer Curl (Dumbbell)", "Dumbbell", "Arms", 87),
  Exercise("Handstand Push Up", "Weighted Bodyweight", "Legs", 88),
  Exercise("Hang Clean (Barbell)", "Barbell", "Olympic", 89),
  Exercise("Hang Snatch (Barbell)", "Barbell", "Olympic", 90),
  Exercise("Hanging Knee Raise", "Reps Only", "Core", 91),
  Exercise("Hanging Leg Raise", "Reps Only", "Core", 92),
  Exercise("High Knee Skips", "Reps Only", "Legs", 93),
  Exercise("Hiking", "Cardio", "Cardio", 94),
  Exercise("Hip Abductor - Close (Machine)", "Machine/Other", "Legs", 95),
  Exercise("Hip Abductor - Open (Machine)", "Machine/Other", "Legs", 96),
  Exercise("Hip Thrust (Barbell)", "Barbell", "Legs", 97),
  Exercise("Hip Thrust (Bodyweight)", "Reps Only", "Legs", 98),
  Exercise("Hip Thrust (Machine)", "Machine/Other", "Legs", 99),
  Exercise("Incline Bench Press (Barbell)", "Barbell", "Chest", 100),
  Exercise("Incline Bench Press (Cable)", "Machine/Other", "Chest", 101),
  Exercise("Incline Bench Press (Dumbbell)", "Dumbbell", "Chest", 102),
  Exercise(
      "Incline Bench Press (Smith Machine)", "Machine/Other", "Chest", 103),
  Exercise("Incline Chest Fly (Dumbbell)", "Dumbbell", "Chest", 104),
  Exercise("Incline Chest Press (Machine)", "Machine/Other", "Arms", 105),
  Exercise("Incline Curl (Dumbbell)", "Dumbbell", "Back", 106),
  Exercise("Incline Row (Dumbbell)", "Dumbbell", "Back", 107),
  Exercise("Inverted Row (Bodyweight)", "Reps Only", "Legs", 108),
  Exercise("Iso-Lateral Chest Press (Machine)", "Machine/Other", "Chest", 109),
  Exercise("Iso-Lateral Row (Machine)", "Machine/Other", "Back", 110),
  Exercise("Jackknife Sit Up", "Weighted Bodyweight", "Core", 111),
  Exercise("Jump Rope", "Reps Only", "Cardio", 112),
  Exercise("Jump Shrug (Barbell)", "Barbell", "Olympic", 113),
  Exercise("Jump Squat", "Reps Only", "Legs", 114),
  Exercise("Jumping Jack", "Reps Only", "Full Body", 115),
  Exercise("Katana (Cable)", "Machine/Other", "Arms", 116),
  Exercise("Katana (Dumbbell)", "Dumbbell", "Arms", 117),
  Exercise("Kettlebell Swing", "Machine/Other", "Full Body", 118),
  Exercise("Kettlebell Turkish Get Up", "Machine/Other", "Full Body", 119),
  Exercise("Kipping Pull Up", "Reps Only", "Back", 120),
  Exercise("Knee Raise (Captain's Chair)", "Weighted Bodyweight", "Core", 121),
  Exercise("Kneeling Pulldown (Band)", "Weighted Bodyweight", "Back", 122),
  Exercise("Knees to Elbows", "Reps Only", "Core", 123),
  Exercise("Lat Pulldown (Cable)", "Machine/Other", "Back", 124),
  Exercise("Lat Pulldown (Machine)", "Machine/Other", "Back", 125),
  Exercise("Lat Pulldown (Single Arm)", "Machine/Other", "Back", 126),
  Exercise(
      "Lat Pulldown - Underhand (Band)", "Weighted Bodyweight", "Back", 127),
  Exercise("Lat Pulldown - Underhand (Cable)", "Machine/Other", "Back", 128),
  Exercise("Lat Pulldown - Wide Grip (Cable)", "Machine/Other", "Back", 129),
  Exercise("Lateral Box Jump", "Reps Only", "Legs", 130),
  Exercise("Lateral Raise (Band)", "Weighted Bodyweight", "Shoulders", 131),
  Exercise("Lateral Raise (Cable)", "Machine/Other", "Shoulders", 132),
  Exercise("Lateral Raise (Dumbbell)", "Dumbbell", "Shoulders", 133),
  Exercise("Lateral Raise (Machine)", "Machine/Other", "Shoulders", 134),
  Exercise("Leg Extension (Machine)", "Machine/Other", "Legs", 135),
  Exercise("Leg Press", "Machine/Other", "Legs", 136),
  Exercise("Lunge (Barbell)", "Barbell", "Legs", 137),
  Exercise("Lunge (Bodyweight)", "Reps Only", "Legs", 138),
  Exercise("Lunge (Dumbbell)", "Dumbbell", "Legs", 139),
  Exercise("Lying Leg Curl (Machine)", "Machine/Other", "Legs", 140),
  Exercise("Mountain Climber", "Reps Only", "Legs", 141),
  Exercise("Muscle Up", "Weighted Bodyweight", "Full Body", 142),
  Exercise("Oblique Crunch", "Reps Only", "Core", 143),
  Exercise("Overhead Press (Barbell)", "Barbell", "Shoulders", 144),
  Exercise("Overhead Press (Cable)", "Machine/Other", "Shoulders", 145),
  Exercise("Overhead Press (Dumbbell)", "Dumbbell", "Shoulders", 146),
  Exercise("Overhead Press (Smith Machine)", "Machine/Other", "Shoulders", 147),
  Exercise("Overhead Squat (Barbell)", "Barbell", "Olympic", 148),
  Exercise("Pec Deck (Machine)", "Machine/Other", "Chest", 149),
  Exercise("Pendlay Row (Barbell)", "Barbell", "Back", 150),
  Exercise("Pistol Squat", "Weighted Bodyweight", "Legs", 151),
  Exercise("Plank", "Duration", "Core", 152),
  Exercise("Power Clean", "Barbell", "Olympic", 153),
  Exercise("Power Snatch (Barbell)", "Barbell", "Olympic", 154),
  Exercise("Preacher Curl (Barbell)", "Barbell", "Arms", 155),
  Exercise("Preacher Curl (Dumbbell)", "Dumbbell", "Arms", 156),
  Exercise("Preacher Curl (Machine)", "Machine/Other", "Arms", 157),
  Exercise("Press Under (Barbell)", "Barbell", "Olympic", 158),
  Exercise("Pull Up", "Weighted Bodyweight", "Back", 159),
  Exercise("Pull Up (Assisted)", "Assisted Body", "Back", 160),
  Exercise("Pull Up (Band)", "Weighted Bodyweight", "Back", 161),
  Exercise("Pullover (Dumbbell)", "Dumbbell", "Chest", 162),
  Exercise("Pullover (Machine)", "Machine/Other", "Chest", 163),
  Exercise("Push Press", "Barbell", "Shoulders", 164),
  Exercise("Push Up", "Weighted Bodyweight", "Chest", 165),
  Exercise("Push Up (Band)", "Weighted Bodyweight", "Chest", 166),
  Exercise("Push Up (Knees)", "Weighted Bodyweight", "Chest", 167),
  Exercise("Rack Pull (Barbell)", "Barbell", "Back", 168),
  Exercise("Reverse Crunch", "Weighted Bodyweight", "Core", 169),
  Exercise("Reverse Curl (Band)", "Weighted Bodyweight", "Arms", 170),
  Exercise("Reverse Curl (Barbell)", "Barbell", "Arms", 171),
  Exercise("Reverse Curl (Dumbbell)", "Dumbbell", "Arms", 172),
  Exercise("Reverse Fly (Cable)", "Machine/Other", "Shoulders", 173),
  Exercise("Reverse Fly (Dumbbell)", "Dumbbell", "Shoulders", 174),
  Exercise("Reverse Fly (Machine)", "Machine/Other", "Shoulders", 175),
  Exercise("Reverse Concentration Curl (Dumbbell)", "Dumbbell", "Arms", 176),
  Exercise("Reverse Plank", "Duration", "Core", 177),
  Exercise("Romanian Deadlift (Barbell)", "Barbell", "Back", 178),
  Exercise("Romanian Deadlift (Dumbbell)", "Dumbbell", "Legs", 179),
  Exercise("Rowing (Machine)", "Machine/Other", "Cardio", 180),
  Exercise("Running", "Cardio", "Cardio", 181),
  Exercise("Running (Treadmill)", "Cardio", "Cardio", 182),
  Exercise("Russian Twist", "Reps Only", "Core", 183),
  Exercise("Seated Calf Raise (Machine)", "Machine/Other", "Legs", 184),
  Exercise("Seated Calf Raise (Plate Loaded)", "Machine/Other", "Legs", 185),
  Exercise("Seated Leg Curl (Machine)", "Machine/Other", "Legs", 186),
  Exercise("Seated Leg Press (Machine)", "Machine/Other", "Legs", 187),
  Exercise("Seated Overhead Press (Barbell)", "Barbell", "Shoulders", 188),
  Exercise("Seated Overhead Press (Dumbbell)", "Dumbbell", "Shoulders", 189),
  Exercise("Seated Palms Up Wrist Curl (Dumbbell)", "Dumbbell", "Arms", 190),
  Exercise("Seated Row (Cable)", "Machine/Other", "Back", 191),
  Exercise("Seated Row (Machine)", "Machine/Other", "Back", 192),
  Exercise("Seated Wide-Grip Row (Cable)", "Machine/Other", "Back", 193),
  Exercise("Shoulder Press (Machine)", "Machine/Other", "Shoulders", 194),
  Exercise("Shoulder Press (Plate Loaded)", "Machine/Other", "Shoulders", 195),
  Exercise("Shrug (Barbell)", "Barbell", "Shoulders", 196),
  Exercise("Shrug (Dumbbell)", "Dumbbell", "Shoulders", 197),
  Exercise("Shrug (Machine)", "Machine/Other", "Back", 198),
  Exercise("Shrug (Smith Machine)", "Machine/Other", "Back", 199),
  Exercise("Side Bend (Band)", "Reps Only", "Core", 200),
  Exercise("Side Bend (Cable)", "Machine/Other", "Core", 201),
  Exercise("Side Bend (Dumbbell)", "Dumbbell", "Core", 202),
  Exercise("Side Plank", "Duration", "Core", 203),
  Exercise("Side Leg Bridge", "Weighted Bodyweight", "Legs", 204),
  Exercise("Sit Up", "Weighted Bodyweight", "Core", 205),
  Exercise("Skating", "Cardio", "Cardio", 206),
  Exercise("Skiing", "Cardio", "Cardio", 207),
  Exercise("Skullcrusher (Barbell)", "Barbell", "Arms", 208),
  Exercise("Skullcrusher (Dumbbell)", "Dumbbell", "Arms", 209),
  Exercise("Snatch (Barbell)", "Barbell", "Olympic", 210),
  Exercise("Snatch Pull (Barbell)", "Barbell", "Olympic", 211),
  Exercise("Snowboarding", "Cardio", "Cardio", 212),
  Exercise("Split Jerk (Barbell)", "Barbell", "Olympic", 213),
  Exercise("Squat (Band)", "Weighted Bodyweight", "Legs", 214),
  Exercise("Squat (Barbell)", "Barbell", "Legs", 215),
  Exercise("Squat (Bodyweight)", "Weighted Bodyweight", "Legs", 216),
  Exercise("Squat (Dumbbell)", "Dumbbell", "Legs", 217),
  Exercise("Squat (Machine)", "Machine/Other", "Legs", 218),
  Exercise("Squat (Smicth Machine)", "Machine/Other", "Legs", 219),
  Exercise("Squat Row (Band)", "Reps Only", "Full Body", 220),
  Exercise("Standing Calf Raise (Barbell)", "Barbell", "Legs", 221),
  Exercise(
      "Standing Calf Raise (Bodyweight)", "Weighted Bodyweight", "Legs", 222),
  Exercise("Standing Calf Raise (Dumbbell)", "Dumbbell", "Legs", 223),
  Exercise("Standing Calf Raise (Machine)", "Machine/Other", "Legs", 224),
  Exercise("Standing Calf Raise (Smith Machine)", "Machine/Other", "Legs", 225),
  Exercise("Step-up", "Reps Only", "Legs", 226),
  Exercise("Stiff Leg Deadlift (Barbell)", "Barbell", "Back", 227),
  Exercise("Stiff Leg Deadlift (Dumbbell)", "Dumbbell", "Legs", 228),
  Exercise("Straight Leg Deadlift (Band)", "Weighted Bodyweight", "Legs", 229),
  Exercise("Stretching", "Duration", "Other", 230),
  Exercise("Strict Military Press (Barbell)", "Barbell", "Shoulders", 231),
  Exercise("Sumo Deadlift (Barbell)", "Barbell", "Back", 232),
  Exercise("Sumo Deadlift High Pull (Barbell)", "Barbell", "Full Body", 233),
  Exercise("Superman", "Reps Only", "Core", 234),
  Exercise("Swimming", "Cardio", "Cardio", 235),
  Exercise("T Bar Row", "Machine/Other", "Back", 236),
  Exercise("Thruster (Barbell)", "Barbell", "Full Body", 237),
  Exercise("Thuster (Kettlebell)", "Machine/Other", "Full Body", 238),
  Exercise("Toes To Bar", "Reps Only", "Core", 239),
  Exercise("Torso Rotation (Machine)", "Machine/Other", "Core", 240),
  Exercise("Trap Bar Deadlift", "Barbell", "Legs", 241),
  Exercise("Triceps Dip", "Weighted Bodyweight", "Arms", 242),
  Exercise("Triceps Dip (Assisted)", "Assisted Body", "Arms", 243),
  Exercise("Triceps Extension", "Barbell", "Arms", 244),
  Exercise("Triceps Extension (Barbell)", "Barbell", "Arms", 245),
  Exercise("Triceps Extension (Cable)", "Machine/Other", "Arms", 246),
  Exercise("Triceps Extension (Dumbbell)", "Dumbbell", "Arms", 247),
  Exercise("Triceps Extension (Machine)", "Machine/Other", "Arms", 248),
  Exercise("Triceps Pushdown (Cable)", "Machine/Other", "Arms", 249),
  Exercise("Upright Row (Barbell)", "Barbell", "Back", 250),
  Exercise("Upright Row (Cable)", "Machine/Other", "Arms", 251),
  Exercise("Upright Row (Dumbbell)", "Dumbbell", "Shoulders", 252),
  Exercise("V Up", "Reps Only", "Core", 253),
  Exercise("Walking", "Cardio", "Cardio", 254),
  Exercise("Wide Pull Up", "Weighted Bodyweight", "Back", 255),
  Exercise("Wrist Roller", "Machine/Other", "Arms", 256),
  Exercise("Yoga", "Duration", "Cardio", 257),
  Exercise("Zercher Squat (Barbell)", "Barbell", "Legs", 258),
];
