import 'package:fitbro/utilities/exercises/exercise_class.dart';

final defaultExercises = [
  Exercise("21", "Barbell", "Arms", 1),
  Exercise("Ab wheel", "Weighted Bodyweight", "Core", 2),
  Exercise("Aerobics", "Duration", "Cardio", 3),
  Exercise("Arnorld Press (Dumbbell)", "Dumbbell", "Shoulders", 4),
  Exercise("Around the World", "Dumbbell", "Chest", 5),
  Exercise("Back Extension", "Weighted Bodyweight", "Back", 6),
  Exercise("Back Extension (Machine)", "Machine/Other", "Back", 7),
  Exercise("Ball Slams", "Machine/Other", "Full Body", 8),
  Exercise("Battle Ropes", "Cardio", "Cardio", 9),
  Exercise("Bench Dip", "Weighted Bodyweight", "Arms", 10),
  Exercise("Bench Press (Barbell)", "Barbell", "Chest", 11),
  Exercise("Bench Press (Cable)", "Machine/Other", "Chest", 12),
  Exercise("Bench Press (Dumbbell)", "Dumbbell", "Chest", 13),
  Exercise("Bench Press (Smith Machine)", "Machine/Other", "Chest", 14),
  Exercise("Bench Press - Close Grip (Barbell)", "Barbell", "Arms", 15),
  Exercise("Bench Press - Wide Grip (Barbell)", "Barbell", "Chest", 16),
  Exercise("Bent Over One Arm Row (Dumbbell)", "Dumbbell", "Back", 17),
  Exercise("Bent Over Row (Band)", "Weighted Bodyweight", "Back", 18),
  Exercise("Bent Over Row (Barbell)", "Barbell", "Back", 19),
  Exercise("Bent Over Row (Dumbbell)", "Dumbbell", "Back", 20),
  Exercise("Bent Over Row - Underhand (Barbell)", "Barbell", "Back", 21),
  Exercise("Bicep Curl (Barbell)", "Barbell", "Arms", 22),
  Exercise("Bicep Curl (Cable)", "Machine/Other", "Arms", 23),
  Exercise("Bicep Curl (Dumbbell)", "Dumbbell", "Arms", 24),
  Exercise("Bicep Curl (Machine)", "Machine/Other", "Arms", 25),
  Exercise("Bicycle Crunch", "Weighted Bodyweight", "Core", 26),
  Exercise("Box Jump", "Reps Only", "Legs", 27),
  Exercise("Box Squat (Barbell)", "Barbell", "Legs", 28),
  Exercise("Bulgarian Split Squat", "Barbell", "Legs", 29),
  Exercise("Burpee", "Reps Only", "Full Body", 30),
];
